### ISSUE TITLE
Update Checker checks for the Version from a wrong URL because the initial Metadata Imports an Extra Link from another Game.

### ISSUE THREAD

**Issue by BestRestUp3300** [zvxfdev/playnite-f95zone#3]
For some reason for the Game for example Home Together it gets an additional link, that makes it think that is the game and the version is supposed to be v34 which prompts up at start up saying there is an update when in fact there isnt one. Is it possible for this to get fixed ?

The Link it gets on top of the original link:

Monolith Bay https://f95zone.to/threads/monolith-bay-v0-34-0-team-monolith.59278/

Also is it possible to add the Version number that is new in the notification.

Edit: 

It also sometimes gets usernames as links, But this doesnt seem to affect the version updates,

Example where it happens Too Much Light it gets:

https://f95zone.to/members/shinekuku.2274053/

Edit2:

Also sometimes it takes the whole thread with name instead of the short version which makes it confused again and says there is an update when there isnt. 

So for example instead of 

https://f95zone.to/threads/130383

It takes an older version of the link

https://f95zone.to/threads/home-together-v0-09-0-home-together-dev.130383/

on top of it and gets confuesed for some reason. 

**Proposed fix for this would be not to scrape any other urls and just the main one which is the one with /threads/130383, otherwise it will be prolly be harder to get the proper links its either that or another way of checking what the version number is.**

Edit3:

After further testing this issue appears on A LOT of GAMES. There are a lot of Bad URLs being obtained.

**Comment by zvxfdev** [comment]
The next release has this all fixed, thanks for making your issue very informative!

The username issue isn't really an issue. (The user is linked in the post, so it's intended behavior).

If you don't like the links scraping feature, I added a new configuration option in settings, "Scrape misc. game links," which you can turn off.

If you find any more issues, please report them!
