### ISSUE TITLE
Can no longer find F95 Games, Have to enter URL Manually then Search.

### ISSUE THREAD

**Issue by Anon1337Elite** [zvxfdev/playnite-f95zone#4]
Title pretty much no results get returned. Only way to manually add the URL then it works.

**Comment by zvxfdev** [comment]
Sorry for being late, very busy. Will fix soon!

**Comment by zvxfdev** [comment]
Nevermind, was just a login issue. If the issue persists after logging out and back in, please make a new issue.

**Comment by Anon1337Elite** [comment]
> Nevermind, was just a login issue. If the issue persists after logging out and back in, please make a new issue.

Yes i forgot to update relogin works :)
